In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\movies_dataset.csv")

In [3]:
df.shape

(1500, 2)

In [4]:
df.head(4)

                      Movie Name                              Genres
0                   Broken Heart              Drama, History, Comedy
1                  Fading Nights          Romance, Biography, Action
2  Beyond the Shattered Frontier       Sport, Sci-Fi, Action, Horror
3                 The Last Heart  Drama, Comedy, Family, Documentary

In [5]:
# Split the genres columns for a list

In [6]:
df[['Genre_1','Genre_2','Genre_3']]=df['Genres'].str.split(',',n=2,expand=True)

In [7]:
df.head(3)

,Movie Name,Genres,Genre_1,Genre_2,Genre_3
0,Broken Heart,"Drama, History, Comedy",Drama,History,Comedy
1,Fading Nights,"Romance, Biography, Action",Romance,Biography,Action
2,Beyond the Shattered Frontier,"Sport, Sci-Fi, Action, Horror",Sport,Sci-Fi,"Action, Horror"

In [8]:
# Remove Genres columns
df.drop(columns="Genres",inplace=True)

In [9]:
df.head(2)

      Movie Name  Genre_1     Genre_2  Genre_3
0   Broken Heart    Drama     History   Comedy
1  Fading Nights  Romance   Biography   Action

In [10]:
# converting into list

In [11]:
df['Genres_list']=df[['Genre_1','Genre_2','Genre_3']].values.tolist()

In [12]:
df.head(2)

      Movie Name  Genre_1     Genre_2  Genre_3                     Genres_list
0   Broken Heart    Drama     History   Comedy      [Drama,  History,  Comedy]
1  Fading Nights  Romance   Biography   Action  [Romance,  Biography,  Action]

In [13]:
df['Genres_list']=df['Genres_list'].apply(lambda x:[i.strip() for i in x if isinstance(i,str)])

In [14]:
df.head(2)

      Movie Name  Genre_1     Genre_2  Genre_3                   Genres_list
0   Broken Heart    Drama     History   Comedy      [Drama, History, Comedy]
1  Fading Nights  Romance   Biography   Action  [Romance, Biography, Action]

In [15]:
from mlxtend.preprocessing import TransactionEncoder

In [23]:
te=TransactionEncoder()
te_ary=te.fit(df['Genres_list']).transform(df['Genres_list'])
genre_df=pd.DataFrame(te_ary,columns=te.columns_)

In [18]:
# Apriori

In [19]:
from mlxtend.frequent_patterns import apriori

In [29]:
frequent_genres=apriori(genre_df,min_support=0.01,use_colnames=True)
frequent_genres.sort_values(by='support',ascending=False).head()

     support              itemsets
8   0.129333   frozenset({Family})
5   0.127333    frozenset({Crime})
13  0.127333  frozenset({Mystery})
7   0.126000    frozenset({Drama})
12  0.126000  frozenset({Musical})

In [30]:
from mlxtend.frequent_patterns import association_rules
rules=association_rules(frequent_genres,metric='lift',min_threshold=1)
rules[['antecedents','consequents','support','confidence','lift']].head()

,antecedents,consequents,support,confidence,lift
0,frozenset({Comedy}),frozenset({Animation}),0.015333,0.127072,1.053081
1,frozenset({Animation}),frozenset({Comedy}),0.015333,0.127072,1.053081
2,frozenset({Horror}),frozenset({History}),0.014000,0.121387,1.034551
3,frozenset({History}),frozenset({Horror}),0.014000,0.119318,1.034551