In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\movies_dataset.csv")

In [3]:
df.shape

(1500, 2)

In [4]:
df.head(2)

      Movie Name                      Genres
0   Broken Heart      Drama, History, Comedy
1  Fading Nights  Romance, Biography, Action

In [11]:
# converting genres word into list
df['genres_list']=df['Genres'].str.split(',').apply(lambda genres:[g.strip() for g in genres])

In [8]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.18.0)
Requirement already satisfied: numpy>=2.3.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (2.5.2)
Requirement already satisfied: pandas>=2.3.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (3.0.5)
Requirement already satisfied: scikit-learn>=1.8.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: joblib>=1.5.2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas>=2.3.3->mlxtend) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)

In [12]:
df.head(5)

,Movie Name,Genres,genres,genres_list
0,Broken Heart,"Drama, History, Comedy",Drama History Comedy,"[Drama, History, Comedy]"
1,Fading Nights,"Romance, Biography, Action",Romance Biography Action,"[Romance, Biography, Action]"
2,Beyond the Shattered Frontier,"Sport, Sci-Fi, Action, Horror",Sport Sci-Fi Action Horror,"[Sport, Sci-Fi, Action, Horror]"
3,The Last Heart,"Drama, Comedy, Family, Documentary",Drama Comedy Family Documentary,"[Drama, Comedy, Family, Documentary]"
4,Savage Rise Rising,"War, History, Drama, Family, Comedy",War History Drama Family Comedy,"[War, History, Drama, Family, Comedy]"

In [9]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [13]:
te=TransactionEncoder()
te_array=te.fit(df['genres_list']).transform(df['genres_list'])

In [ ]:
genre_encoded_df=pd.DataFrame(te_array,columns=te.