In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\archive (3)\movies.csv")

In [5]:
df.head(1)

,Unnamed: 0,URLs,Year_Released,Title,IMDB Ids,Cast,Plot_Summary,Review,Genre,Released Date,Plot Keywords,Duration,Age of content
0,0,https://www.imdb.com//title/tt1187043/?ref_=fn...,2009.0,3 Idiots,tt1187043,"With Aamir Khan, Madhavan, Sharman Joshi, Kare...","""Two friends are searching for their long lost...","""I was lucky to see the first day show of 3 id...","[""Comedy"",""Drama""]","""2009-12-25""","""papadum,hairy chest,against the system,coming...","""2H50M""",13.0

In [6]:
df=df[['Title','Genre']]

In [7]:
df.head(2)

               Title               Genre
0          3 Idiots   ["Comedy","Drama"]
1  Taare Zameen Par   ["Drama","Family"]

In [8]:
df['Genre'][6]

'["Drama","Romance"]'

In [9]:
df['Genre']=df['Genre'].map(lambda val:np.nan if val==" " else val)

In [10]:
df.isnull().sum()

Title      0
Genre    681
dtype: int64

In [11]:
import ast
def convert_into_list(value):
    if isinstance(value,str):
        return ast.literal_eval(value)
    return value

In [12]:
df['Genre']=df['Genre'].apply(convert_into_list)

In [13]:
df.head(3)

               Title                    Genre
0          3 Idiots           [Comedy, Drama]
1  Taare Zameen Par           [Drama, Family]
2                PK   [Comedy, Drama, Sci-Fi]

In [14]:
df.isnull().sum()

Title      0
Genre    681
dtype: int64

In [15]:
df=df.dropna()

In [16]:
df=df.drop_duplicates(subset='Title').reset_index(drop=True)

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
from sklearn.preprocessing import MultiLabelBinarizer

In [19]:
df.shape

(2429, 2)

In [20]:
encoder=MultiLabelBinarizer()

In [21]:
df.index=df['Title']

In [ ]:
df['Title']=df['Title'].

In [22]:
df.head()

                               Title                       Genre
Title
3 Idiots                   3 Idiots              [Comedy, Drama]
Taare Zameen Par   Taare Zameen Par              [Drama, Family]
PK                               PK      [Comedy, Drama, Sci-Fi]
Dangal                       Dangal   [Action, Biography, Drama]
Rang De Basanti     Rang De Basanti       [Comedy, Crime, Drama]

In [23]:
df=df

In [24]:
df=pd.DataFrame(
    encoder.fit_transform(df['Genre']),
    index=df.index,
    columns=encoder.classes_
)

In [25]:
df.head()

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,...,News,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western
Title,,,,,,,,,,,,,,,,,,,,,
3 Idiots,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Taare Zameen Par,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
PK,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
Dangal,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Rang De Basanti,0,0,0,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
def recommend(movie,n=5):
    movie=movie.strip().lower()
    if movie not in df.index:
        return "Movie Not Found!"

In [30]:
recommend('PK ')

'Movie Not Found!'

In [29]:
df.index

Index(['3 Idiots ', 'Taare Zameen Par ', 'PK ', 'Dangal ', 'Rang De Basanti ',
       'Lagaan: Once Upon a Time in India ', 'My Name Is Khan ',
       'Swades: We, the People ', 'Gangs of Wasseypur ', 'Barfi! ',
       ...
       'Haseenon Ka Devata ', 'Mazloom ', 'Mere Genie Uncle ',
       'Kaanch Ki Deewar ', 'Woh Jo Hasina ', 'Swarg Jaisaa Ghar ', 'Mehmaan ',
       'Sorry Daddy ', 'Raadha Aur Seeta ', 'Calapor '],
      dtype='str', name='Title', length=2429)