In [18]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\data_set.csv")

In [20]:
df.shape

(999, 7)

In [21]:
df.head(3)

,Product Name,Category,tag1,tag2,tag3,tag4,tag5
0,Smartphone,Electronics,Mobile,Technology,Gadget,Communication,Smart
1,Laptop,Electronics,Computer,Technology,Portable,Productivity,High Performance
2,Smartwatch,Electronics,Smart,Wearable,Health,Fitness,Technology

In [22]:
df=df.drop_duplicates(subset="Product Name").reset_index(drop=True)

In [23]:
df.shape

(790, 7)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 790 entries, 0 to 789
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  790 non-null    str
 1   Category      790 non-null    str
 2   tag1          790 non-null    str
 3   tag2          790 non-null    str
 4   tag3          790 non-null    str
 5   tag4          790 non-null    str
 6   tag5          764 non-null    str
dtypes: str(7)
memory usage: 112.8 KB

In [28]:
# Preprocessing
for col in ["Category"]:
    df[col]=df[col].fillna("").astype(str).str.strip().str.lower()

In [29]:
df.head()

,Product Name,Category,tag1,tag2,tag3,tag4,tag5
0,Smartphone,electronics,Mobile,Technology,Gadget,Communication,Smart
1,Laptop,electronics,Computer,Technology,Portable,Productivity,High Performance
2,Smartwatch,electronics,Smart,Wearable,Health,Fitness,Technology
3,Headphones,electronics,Audio,Music,Gadget,Wireless,Comfortable
4,Tablet,electronics,Portable,Technology,Touchscreen,Entertainment,Compact

In [ ]:
# Build txn one item for the list
def build_transaction(row) --> list[str]: